# Generated by Django 5.0.3 on 2024-04-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_category_image_alter_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='games', to='portal.category'),
        ),
    ]
