# Generated by Django 5.0.4 on 2024-04-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_alter_app_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='static/img/covers/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, upload_to='static/img/icons/'),
        ),
    ]
