# Generated by Django 5.0.4 on 2024-04-30 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_alter_app_cover_photo_alter_app_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='app_store.app'),
        ),
    ]
